### ISSUE TITLE
文件检索器(翻页第一版)

### ISSUE THREAD

**Issue by acid-fish** [RavenHogWarts/Snippets#1]
![PixPin_2024-06-01_12-43-40](https://github.com/RavenHogWarts/Snippets/assets/51695006/062f3734-2649-462f-b37c-6b019bce8e0b)
求助！其他案例成功的，唯独这个不知道哪里出错了，设置不成功，语句“page["author"]中的author替换为自己的作者属性“是怎么理解的，将author替换成具体的作者名吗？

**Comment by RavenHogWarts** [comment]
就是我的文档属性中author用来记录作者，可能有的人的属性是Author，Authors这样，需要改成自己设置的

**Comment by RavenHogWarts** [comment]
https://www.bilibili.com/video/BV1nZ42177bD/
可以看看我这个文件检索器的补充视频

**Comment by acid-fish** [comment]
已经成功了，谢谢
