### ISSUE TITLE
components 筛选器如何实现多个标签筛选

### ISSUE THREAD

**Issue by unscrewnk** [RavenHogWarts/Snippets#2]
![image](https://github.com/user-attachments/assets/e2788328-b72a-4ad4-90d0-e65e45ce3a73)
使用第一版的筛选器，标签和作者都只能选择一个，能否实现自由添加

**Comment by RavenHogWarts** [comment]
> ![image](https://private-user-images.githubusercontent.com/164011304/360244907-e2788328-b72a-4ad4-90d0-e65e45ce3a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjQwMDAsIm5iZiI6MTcyNDMyMzcwMCwicGF0aCI6Ii8xNjQwMTEzMDQvMzYwMjQ0OTA3LWUyNzg4MzI4LWI3MmEtNGFkNC05MGQwLWU2NWU0NWNlM2E3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQxMDQ4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzlkNzRiYTBiNDdmODYyNGEzNDYwYTNjYjI0NTQ4NmZjNDAxYWIzODk2ZjViOWRjODJiMmM4NWI3OTNiMmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rHbQEIwx-ACUQaMvunjRY0WrT5anL7_P6pCa_RUfYjo) 使用第一版的筛选器，标签和作者都只能选择一个，能否实现自由添加

可以参考飞书上的第二版
https://wxycbt0cjk.feishu.cn/wiki/D6aewPq0ciFWevko7rdcQ2mOn8f
